version: "3.9"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.dev.env
    depends_on:
      - db
  db:
    image: timescale/timescaledb-ha:pg14-latest
    volumes:
      - postgres_data:/home/postgres/pgdata/data
    env_file:
      - ./.dev.db.env
    hostname: postgres

volumes:
  postgres_data: